name: Production CI

on:
  push:
    branches:
      - prod  # Only trigger on pushes to prod
  pull_request:
    types: [closed]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send notification to Discord
        run: |
          curl -H "Content-Type: application/json" \
          -X POST "${{ secrets.DISCORD_WEBHOOK_URL }}" \
          -d '{
            "username": "GitHub Notifier",
            "avatar_url": "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png",
            "embeds": [{
              "title": "🚀 Deployment Alert!",
              "description": "New changes have been merged into **prod** in `${{ github.repository }}` by **${{ github.actor }}**",
              "color": 5814783,
              "timestamp": "'$(date --utc +%Y-%m-%dT%H:%M:%SZ)'",
              "fields": [
                {
                  "name": "Commit",
                  "value": "[View Commit](https://github.com/${{ github.repository }}/commit/${{ github.sha }})"
                },
                {
                  "name": "Branch",
                  "value": "prod"
                }
              ]
            }]
          }'
